<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Loja Web Reis</title>
    <link rel="icon" href="/resources/assets/img/logo.jpg" style="height: 10px; width: 10px">
    <link rel="stylesheet" type="text/css" href="<?= PATH ?>/public/css/estilo.css">
    <link rel="stylesheet" type="text/css" href="<?=  PATH ?>/public/css/style-login.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="<?=PATH ?>/resources/assets/img/logo.jpg" style="height: 50px; width: 50px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent" >
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= PATH ?>/" alt = "produtos">Produtos</a>
                </li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item"><a class="nav-link" href="<?= PATH ?>/login">Entrar</a></li>
            </ul>
        </div>
    </div>
</nav>

