<div class="body-login">
    <div class="container">
        <?php if(isset($erro)):?>
            <div class="alert alert-danger"><?= isset($erro) ? $erro : '' ?></div>
        <?php endif; ?>
        <form class="form-signin" action = "<?= PATH ?>/login" method="post">
            <h2 class="form-signin-heading">Faça seu login</h2>
            <label for="inputEmail" class="sr-only" >Endereço de email</label>
            <input type="email" id="inputEmail" class="form-control" placeholder="Endereço de email" name="email" require>
            <label for="inputPassword" class="sr-only" >Senha</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Senha" name="pass" equire>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>


        </form>

    </div>

</div>
