<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="<?= PATH ?>/admin/products"> Voltar para lista de produtos</a>
            <h2>Visualizar Produto</h2>
            <h3>Cod: <?= $product->id_product ?> </h3>
            <h3>Produto: <?= $product->name_product ?></h3>
            <h3>Quantidade: <?= $product->number_product ?></h3>
        </div>
    </div>
</div>